version: "3"
services:
  api:
    container_name: wizardmc-api
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        PORT: 3333
        DB_CONNECTION: pg
        DB_HOST: wizardmc-db
        DB_PORT: 5432
        DB_USER: api
        DB_NAME: wizardmc
        DB_PASSWORD: ${PG_PASSWORD}
        DB_DEBUG: "false"
        REDIS_CONNECTION: local
        REDIS_HOST: 127.0.0.1
        REDIS_PORT: 6379
        REDIS_PASSWORD:
    ports:
      - 3333:3333
    depends_on:
      - db
  frontend:
    container_name: wizardmc-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:300
    depends_on:
      - api
  db:
    container_name: wizardmc-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: wizardmc
      POSTGRES_USER: api
      POSTGRES_PASSWORD: eVRYDgOKi9K9bzsZcqbRIPkl2Gr3aqYnqfAcIOzl0N2RpNGHbq22zB7Kb873Q5YiwOmzJ1q352Jr95C1TM/2+w==
